spring:
  profiles: test
  datasource:
    url:  jdbc:mysql://localhost:3306/sns?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  sql:
    init:
      mode: always
      platform: mysql

  jpa:
    database: mysql
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

cloud:
  aws:
    s3:
      bucketName: spring-sns
    region:
      static: ap-northeast-2
    stack:
      auto: false